/**
 * Persistence for File System Access API handles.
 *
 * File handles are stored in IndexedDB (not chrome.storage.local) because
 * only a structured-cloneable FileSystemHandle can survive the storage round
 * trip. chrome.storage.local stringifies values and would break the handle.
 *
 * ponytail: One shared DB and one object store for all local file/directory
 * handles. IDs are generated by the caller (settings UUIDs). Permission must
 * be re-verified before every read, so this module exposes a helper for that.
 */

const DB_NAME = 'cell-local-file-handles';
const STORE_NAME = 'handles';
const DB_VERSION = 1;

interface StoredHandle {
  readonly id: string;
  readonly handle: FileSystemHandle;
  readonly savedAt: number;
}

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    request.onerror = () => reject(request.error ?? new Error('Failed to open IndexedDB'));
    request.onsuccess = () => resolve(request.result);
    request.onupgradeneeded = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: 'id' });
      }
    };
  });
}

/** Persist a file or directory handle under an id. */
export async function saveFileHandle(id: string, handle: FileSystemHandle): Promise<void> {
  const db = await openDb();
  try {
    const tx = db.transaction(STORE_NAME, 'readwrite');
    const store = tx.objectStore(STORE_NAME);
    const record: StoredHandle = { id, handle, savedAt: Date.now() };
    return new Promise((resolve, reject) => {
      const request = store.put(record);
      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error ?? new Error('Failed to save file handle'));
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error ?? request.error ?? new Error('Transaction error'));
    });
  } finally {
    db.close();
  }
}

/** Retrieve a previously saved handle, or undefined if missing. */
export async function getFileHandle(id: string): Promise<FileSystemHandle | undefined> {
  const db = await openDb();
  try {
    const tx = db.transaction(STORE_NAME, 'readonly');
    const store = tx.objectStore(STORE_NAME);
    return new Promise((resolve, reject) => {
      const request = store.get(id);
      request.onsuccess = () => {
        const record = request.result as StoredHandle | undefined;
        resolve(record?.handle);
      };
      request.onerror = () => reject(request.error ?? new Error('Failed to load file handle'));
    });
  } finally {
    db.close();
  }
}

/** Delete a stored handle. */
export async function deleteFileHandle(id: string): Promise<void> {
  const db = await openDb();
  try {
    const tx = db.transaction(STORE_NAME, 'readwrite');
    const store = tx.objectStore(STORE_NAME);
    return new Promise((resolve, reject) => {
      const request = store.delete(id);
      request.onsuccess = () => resolve();
      request.onerror = () => reject(request.error ?? new Error('Failed to delete file handle'));
    });
  } finally {
    db.close();
  }
}

/** List all stored handle ids. */
export async function listFileHandleIds(): Promise<readonly string[]> {
  const db = await openDb();
  try {
    const tx = db.transaction(STORE_NAME, 'readonly');
    const store = tx.objectStore(STORE_NAME);
    return new Promise((resolve, reject) => {
      const request = store.getAllKeys();
      request.onsuccess = () => resolve(request.result as string[]);
      request.onerror = () => reject(request.error ?? new Error('Failed to list file handles'));
    });
  } finally {
    db.close();
  }
}

/**
 * Verify (and request if needed) permission for a file or directory handle.
 * Returns true only if the user grants/retains permission.
 */
export async function verifyPermission(
  handle: FileSystemHandle,
  mode: 'read' | 'readwrite' = 'read',
): Promise<boolean> {
  const options = { mode };
  const status = await handle.queryPermission(options);
  if (status === 'granted') return true;
  const afterRequest = await handle.requestPermission(options);
  return afterRequest === 'granted';
}
