import { parseIPA } from './ipaSegmenter';
import { estimateTimeline } from './phonemeTimelineEstimator';
import type { Phoneme, PronunciationResult, PronunciationAudio, PronunciationMetadata } from '../types';
import type { EspeakPhonemeEngine } from './espeakPhonemeEngine';

export interface PronunciationEngine {
  /**
   * Convert text to a structured PronunciationResult.
   *
   * @param text - word or short phrase to pronounce
   * @param language - BCP-47 / ISO language code
   * @param audio - optional word audio with duration; if null, timeline is all zeros
   */
  readonly toPronunciation: (
    text: string,
    language: string,
    audio?: PronunciationAudio | null,
  ) => Promise<PronunciationResult>;
}

/** Shared metadata for the eSpeak-phonemes engine. */
const ESPEAK_METADATA: PronunciationMetadata = {
  engine: 'espeak-phonemes',
  engineVersion: '0.0.5',
  source: 'espeak',
};

function buildResult(
  text: string,
  language: string,
  ipa: string,
  audio: PronunciationAudio | null,
): PronunciationResult {
  const rawPhonemes = parseIPA(ipa);
  const phonemes: readonly Phoneme[] = audio
    ? estimateTimeline(rawPhonemes, audio.duration * 1000)
    : rawPhonemes;

  return {
    text,
    language,
    ipa,
    phonemes,
    audio: audio ?? null,
    metadata: ESPEAK_METADATA,
  };
}

/**
 * Create a pronunciation engine backed by eSpeak-phonemes.
 *
 * Audio is passed in rather than generated by this engine so the caller can
 * choose the audio source (native, Supertonic, browser TTS, eSpeak) separately.
 */
export function createPronunciationEngine(
  phonemeEngine: EspeakPhonemeEngine,
): PronunciationEngine {
  return {
    async toPronunciation(text, language, audio = null) {
      const ipa = await phonemeEngine.toIpa(text, { voice: language === 'en-us' ? 'en-us' : 'en' });
      return buildResult(text, language, ipa, audio ?? null);
    },
  };
}
