import { createEspeakPhonemeEngine } from './espeakPhonemeEngine';
import { createPronunciationEngine } from './pronunciationEngine';

/**
 * Shared pronunciation engine for the dictionary popup.
 *
 * Lazily initializes the eSpeak WASM on first use. The audio is provided
 * separately by the caller (e.g. a selected AudioItem URL) rather than
 * generated by the engine itself in Option A.
 */
export const pronunciationEngine = createPronunciationEngine(createEspeakPhonemeEngine());
