/**
 * InnerTube fallback — POST `/youtubei/v1/player` (ANDROID client) to get
 * caption tracks WITHOUT PO Token requirement.
 *
 * Browser verify (2026-07-04): YouTube's WEB client `ytInitialPlayerResponse`
 * caption tracks ALL have `exp=xpe` (PO Token required). The PO Token is
 * generated by YouTube's player JS at runtime and is ephemeral (single-use).
 * Fetching VTT without PO Token returns empty (200 OK, 0 bytes).
 *
 * The ANDROID InnerTube client returns caption tracks with `exp=null` (NO
 * PO Token required) — verified on `YQHsXMglC9A` (Adele - Hello). The ANDROID
 * client works from the browser's fetch (no User-Agent override needed — the
 * API doesn't strictly validate User-Agent for the ANDROID client).
 *
 * Constraint (ADR-020 Contract 5 revised): content scripts CANNOT set the
 * `User-Agent` header (forbidden header — MDN). However, the ANDROID InnerTube
 * client works WITHOUT an ANDROID User-Agent — the API accepts the browser's
 * default User-Agent. This was verified empirically (browser verify 2026-07-04).
 *
 * Sources:
 * - Browser verify 2026-07-04: ANDROID client returns tracks with exp=null
 * - yt-dlp `_video.py` (ANDROID client for PO Token bypass)
 * - github.com/nadimtuhin/ytranscript/HOW_IT_WORKS.md
 * - ADR-020 Contract 5 (revised: ANDROID client feasible without User-Agent override)
 */
import type { YouTubeCaptionTrack } from './youtubeSubtitleDetector';
import { extractCaptionTracks } from './youtubeSubtitleDetector';

/** Regex to extract `INNERTUBE_API_KEY` from page HTML (MAIN-world side). */
const INNERTUBE_API_KEY_RE = /"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"/;

/** Regex to extract `INNERTUBE_CONTEXT` client version from page HTML. */
const CLIENT_VERSION_RE = /"clientVersion"\s*:\s*"([^"]+)"/;

/** InnerTube API endpoint. */
const INNERTUBE_ENDPOINT = 'https://www.youtube.com/youtubei/v1/player';

/** ANDROID client version (kept recent — update if YouTube rejects old versions). */
const ANDROID_CLIENT_VERSION = '20.10.38';

/** InnerTube client context. */
interface InnerTubeContext {
  readonly clientName: string;
  readonly clientVersion: string;
  readonly visitorData?: string;
}

/**
 * Extract the InnerTube API key from page HTML.
 *
 * Called from the MAIN-world script (page HTML is available there); the key
 * is forwarded to the background via `postMessage` so the background SW can
 * call InnerTube without re-fetching the page.
 *
 * @returns the API key string, or `null` when not found.
 */
export function extractInnertubeApiKey(html: string): string | null {
  const match = html.match(INNERTUBE_API_KEY_RE);
  return match?.[1] ?? null;
}

/**
 * Extract the WEB client version from page HTML (falls back to a recent
 * stable version when not found, so the fallback still works if YouTube
 * changes the HTML structure).
 */
export function extractClientVersion(html: string): string {
  const match = html.match(CLIENT_VERSION_RE);
  return match?.[1] ?? '2.20240701.00.00';
}

/**
 * Build the InnerTube POST body for the ANDROID client context.
 *
 * The ANDROID client returns caption tracks WITHOUT `exp=xpe` (NO PO Token
 * required) — verified browser verify 2026-07-04. The ANDROID client works
 * from the browser's default User-Agent (no override needed).
 */
function buildInnerTubeBody(
  videoId: string,
  visitorData?: string,
): Record<string, unknown> {
  const client: Record<string, unknown> = {
    clientName: 'ANDROID',
    clientVersion: ANDROID_CLIENT_VERSION,
  };
  if (visitorData) {
    client.visitorData = visitorData;
  }
  return {
    context: { client },
    videoId,
  };
}

/**
 * Fetch caption tracks via the InnerTube API (ANDROID client — NO PO Token).
 *
 * CAN be called from the BACKGROUND service worker OR the MAIN world (the
 * ANDROID client accepts the browser's default User-Agent). The background SW
 * is preferred (consistent with ADR-020 Contract 5 — centralizes fetch logic).
 *
 * @param videoId - YouTube video ID (e.g. `dQw4w9WgXcQ`).
 * @param apiKey - InnerTube API key (extracted from page HTML by the MAIN
 *   world script).
 * @param visitorData - Optional visitorData from `ytcfg.get('INNERTUBE_CONTEXT')
 *   .client.visitorData` (improves success rate — provides session context).
 * @returns `YouTubeCaptionTrack[]` (empty if the response has no captions or
 *   the request fails). ANDROID client tracks have `exp=null` (NO PO Token).
 */
export async function fetchCaptionTracksViaInnerTube(
  videoId: string,
  apiKey: string,
  visitorData?: string,
): Promise<YouTubeCaptionTrack[]> {
  const url = `${INNERTUBE_ENDPOINT}?key=${encodeURIComponent(apiKey)}`;
  const body = buildInnerTubeBody(videoId, visitorData);

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      console.warn(
        `[youtube-innertube] HTTP ${response.status} for videoId=${videoId}`,
      );
      return [];
    }
    const json: unknown = await response.json();
    const tracks = extractCaptionTracks(json);
    console.log(
      `[youtube-innertube] ANDROID client returned ${tracks.length} tracks for videoId=${videoId}`,
    );
    return tracks;
  } catch (err) {
    console.warn(
      `[youtube-innertube] fetch failed for videoId=${videoId}:`,
      err,
    );
    return [];
  }
}

/**
 * Build the InnerTube ANDROID client context (exported for testing).
 */
export function buildInnerTubeContext(
  clientVersion: string,
  visitorData?: string,
): InnerTubeContext {
  if (visitorData) {
    return { clientName: 'ANDROID', clientVersion, visitorData };
  }
  return { clientName: 'ANDROID', clientVersion };
}
